---
- name: Register infrastructure server to Satellite
  hosts: all
  tasks:
    - name: install insights client on host machines
      yum:
        name: insights-client
        state: latest

    - name: register host to insights service
      command: insights-client --register
      args:
        warn: no
