---
- name: Register infrastructure server to Satellite
  hosts: "{{ idm_hosts }}"
  tasks:
    #- name: clean existing registration and start fresh
    #  redhat_subscription:
    #   state: absent

    - name: install katello-ca-consumer-latest certificate
      command: yum localinstall -y http://sat-server.beniaris.com/pub/katello-ca-consumer-latest.noarch.rpm
      args:
        warn: no

    - name: register node to the Satellite server
      redhat_subscription:
        state: present
        activationkey: {{ activation_key }}
        org_id: Beniaris

    - name: install katello agent on the server
      yum:
        name: katello-agent
        state: latest
